### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by Sebybastian** [DmitrijsNau/raindle#2]
Presently, the game is quite unfriendly to colorblind people, as well as color being somewhat poorly defined. I would recommend either adding a reference sheet or changing this category entirely (maybe shape instead of color?)

**Comment by DmitrijsNau** [comment]
Thank you for your advice, I will admit I did not consider color-blindness when first developing this game and for this I apologize. I will
be taking your advice and add a color-blind mode to change the colors on the answers, and add a reference sheet for colors for the items. Thank you so much for your feedback!
Dmitrijs Naudzuns
BS in Computer Science
University at Buffalo 2024
(716)-249-7286

________________________________
From: Sebybastian ***@***.***>
Sent: Friday, May 17, 2024 10:39 AM
To: DmitrijsNau/raindle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DmitrijsNau/raindle] Color (Issue #2)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Presently, the game is quite unfriendly to colorblind people, as well as color being somewhat poorly defined. I would recommend either adding a reference sheet or changing this category entirely (maybe shape instead of color?)

**Comment by DmitrijsNau** [comment]
Colorblind mode and a lookup table for colors has been added! Thank you so much for your feedback on my game :)
